site_name: Medieval Empires
site_url: https://empires.rat.pink/
site_description: Medieval Empires Game - DiamondFire
site_author: MozzarellaRat

repo_url: https://github.com/MozzarellaRat/empire.rat.pink
edit_uri: blob/master/docs/

nav:
  - Home: index.md
